run:
  deadline: "2m"

linters-settings:
  govet:
    check-shadowing: true

  gocyclo:
    min-complexity: 16.0

  maligned:
    suggest-new: true

  goconst:
    min-len: 2.0
    min-occurrences: 3.0

  misspell:
    locale: "US"

linters:
  enable-all: true
  disable:
    - "maligned"
    - "lll"
    - "gas"
    - "dupl"
    - "prealloc"

issues:
  max-per-linter: 0
  max-same: 0
  exclude-rules:
    - path: "main_test.go"
      text: "package should be `main_test` instead of `main`"
    - path: "main.go"
      text: "appendAssign: append result not assigned to the same slice"
    - path: "main.go"
      text: "`debug` is a global variable"
